[env:ttgo-t-beam]
platform = espressif32
board = ttgo-t-beam
framework = arduino
monitor_speed = 115200

lib_deps =
    mikalhart/TinyGPSPlus @ ^1.0.3
    sandeepmistry/LoRa @ ^0.8.0
    mathertel/OneButton @ ^2.5.0
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9
    lewisxhe/XPowersLib @ ^0.2.1
    upload_port = COM5